export const CONTENT_LIMITS = {
  MAX_POST_LENGTH: 5000,
  MAX_COMMENT_LENGTH: 2000,
  MAX_BIO_LENGTH: 500,
  MAX_DISPLAY_NAME_LENGTH: 50,
  MIN_DISPLAY_NAME_LENGTH: 2,
  MAX_GROUP_NAME_LENGTH: 100,
  MAX_GROUP_DESCRIPTION_LENGTH: 1000,
  MAX_GROUP_RULES: 10,
  MAX_MEDIA_PER_POST: 4,
  MAX_MENTIONS_PER_CONTENT: 10,
} as const;

export const SOCIAL_LIMITS = {
  MAX_BLOCKS: 1000,
} as const;

export const MEDIA_LIMITS = {
  MAX_FILE_SIZE_BYTES: 10 * 1024 * 1024,
} as const;

export const SECURITY_LIMITS = {
  PASSWORD_MIN_LENGTH: 12,
  MAX_LOGIN_ATTEMPTS: 5,
  LOCKOUT_DURATION_MINUTES: 15,
  MAX_ACTIVE_SESSIONS: 5,
} as const;

export const PAGINATION = {
  DEFAULT_PAGE_SIZE: 20,
  MAX_PAGE_SIZE: 100,
  MIN_PAGE: 1,
} as const;

export const CACHE_TTL = {
  SHORT: 30,
  MEDIUM: 300,
  LONG: 3600,
  DAY: 86400,
} as const;

export const AUTH = {
  ACCESS_TOKEN_TTL: 900,
  REFRESH_TOKEN_TTL: 604800,
  MAX_SESSIONS: 5,
} as const;
